// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrja3MG30Gql5PcIlP6T_tCpgWS1RlcSQ',
    appId: '1:335642642253:web:0e6ccbe228aae2e98e1904',
    messagingSenderId: '335642642253',
    projectId: 'fruit-hub-23931',
    authDomain: 'fruit-hub-23931.firebaseapp.com',
    storageBucket: 'fruit-hub-23931.appspot.com',
    measurementId: 'G-QWZGL33GT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD23SECYHOaZH9BkI-cCuWrlEjycbbLACQ',
    appId: '1:335642642253:android:dc2472dc11e725f98e1904',
    messagingSenderId: '335642642253',
    projectId: 'fruit-hub-23931',
    storageBucket: 'fruit-hub-23931.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQEkA3Jz9dxVdMV_8SS38IguhHtQRfRpM',
    appId: '1:335642642253:ios:2bc113778ca09a8e8e1904',
    messagingSenderId: '335642642253',
    projectId: 'fruit-hub-23931',
    storageBucket: 'fruit-hub-23931.appspot.com',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQEkA3Jz9dxVdMV_8SS38IguhHtQRfRpM',
    appId: '1:335642642253:ios:2bc113778ca09a8e8e1904',
    messagingSenderId: '335642642253',
    projectId: 'fruit-hub-23931',
    storageBucket: 'fruit-hub-23931.appspot.com',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrja3MG30Gql5PcIlP6T_tCpgWS1RlcSQ',
    appId: '1:335642642253:web:9dbbcbafaf4b87c88e1904',
    messagingSenderId: '335642642253',
    projectId: 'fruit-hub-23931',
    authDomain: 'fruit-hub-23931.firebaseapp.com',
    storageBucket: 'fruit-hub-23931.appspot.com',
    measurementId: 'G-5R037T2SYF',
  );
}
